version: "3.9"
services:
  db:
    build: ./docker/db
    ports:
      - "8306:3306"
    volumes:
      - "/etc/mysql/conf.d:/etc/mysql/conf.d"
      - "/var/lib/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "Zerkalo82"
      MYSQL_DATABASE: "test9"
      MYSQL_USER: "root"
    restart: always


  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "5000:9090"
    container_name: cont_app
    volumes:
      - ".:/test9"
      - "./logs:/test9/logs"
    depends_on:
      - db
    restart: always

#  adminer:
#    build: ./docker/adminer
#    ports:
#      - "6080:8080"
#    restart: always



